python solution.py --s "()"
python solution.py --s "()[]{}"
python solution.py --s "(]"
python solution.py --s ")("
python solution.py --s "([)]"
python solution.py --s "{[]}"
python solution.py --s "]"